using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

namespace Hall9k.Domain.Features.Project;

/// <summary>
/// What checking a piece of prose against a project's <see cref="WritingConventions"/> found.
/// <para>
/// <see cref="Text"/> is what the caller should post: unchanged when the prose was already clean,
/// rewritten when every hit had a mechanical fix, and the original when
/// <see cref="Refusal"/> says there was one that did not (a caller that refuses posts nothing at
/// all, so the text is carried only so the log line can quote it).
/// </para>
/// </summary>
/// <param name="Text">The prose as it should be posted.</param>
/// <param name="Rewrites">One line per fix actually applied, for the caller's own log; empty when nothing changed.</param>
/// <param name="Refusal">Why this prose cannot be posted at all, naming the rule; null when it can.</param>
public sealed record WritingConventionsVerdict(
    string Text,
    IReadOnlyList<string> Rewrites,
    string? Refusal)
{
    /// <summary>Whether the prose must not be posted.</summary>
    public bool Refused => Refusal is not null;

    /// <summary>Whether the prose went through untouched.</summary>
    public bool Clean => Refusal is null && Rewrites.Count == 0;

    /// <summary>The verdict on prose no rule applied to, and on prose there was none of.</summary>
    public static WritingConventionsVerdict Untouched(string text) => new(text, [], null);
}

/// <summary>
/// The half of a project's <see cref="WritingConventions"/> a machine can actually check, run
/// over every piece of composed prose the platform itself posts to GitHub under the owner's
/// login: a pull request's title and body, a top-level comment answering a review, and a
/// reviewer's own review note.
/// <para>
/// Two rules, and only two, because only two of the default conventions are decidable without
/// reading the prose: an em dash (U+2014), and an AI attribution string. "Full sentences over
/// telegraphic fragments" is not checkable and is deliberately not attempted; it reaches the
/// composing agent through the prompt, which is where a judgment rule belongs. Saying which half
/// is which out loud is the point: a checker that claimed the whole convention would let the
/// unchecked half rot behind a green light.
/// </para>
/// <para>
/// A hit is fixed where the fix is mechanical and refused where it is not. An em dash always has
/// one (<see cref="Punctuation"/> picks a comma, a semicolon or a colon by context, and a dash
/// with no clause on one side of it is removed outright). An
/// attribution alone on its own line always has one, which is to drop the line. An attribution
/// welded into a sentence a person wrote has none: deleting the sentence would delete their
/// words, and leaving it would post the attribution, so the caller is told to post nothing and
/// to say so in its log. Nothing here ever fails a run — a convention miss is a style defect, and
/// stranding finished, gated work over one would cost far more than the miss does.
/// </para>
/// <para>
/// Origin incident (2026-09-09): see <see cref="WritingConventions"/>, whose own doc carries it.
/// The precedent for treating an em dash as a mechanically checkable token is
/// <c>Hall9k.Daemon.Review.ReviewVerdictValidation</c>, which already blocks one outright in a
/// reviewer's verdict text.
/// </para>
/// </summary>
public static partial class WritingConventionsCheck
{
    /// <summary>U+2014, written as its code point for the reason it is banned: it is easy to mistake for a hyphen.</summary>
    public const char EmDash = (char)0x2014;

    /// <summary>
    /// The words a conventions text uses when it is banning em dashes. Probed rather than assumed,
    /// per <see cref="WritingConventions.States"/>: a project that rewrote its conventions and left
    /// the rule out gets prose posted exactly as its agent wrote it.
    /// </summary>
    private static readonly string[] EmDashCues = ["em dash", "em-dash", "emdash", "U+2014"];

    /// <summary>The words a conventions text uses when it is banning AI attribution, probed the same way.</summary>
    private static readonly string[] AttributionCues =
        ["attribution", "co-authored-by", "coauthored", "generated with", "generated by"];

    /// <summary>
    /// The attribution strings themselves. Short and literal on purpose: this list is what the
    /// check actually enforces, and every entry here is a phrase observed in agent-composed prose
    /// rather than one imagined for completeness (AGENTS.md: never guess at unobserved facts).
    /// </summary>
    private static readonly string[] AttributionPhrases =
    [
        "generated with claude",
        // The footer as it is actually written, with the tool name as a markdown link: "Generated
        // with [Claude Code](https://claude.ai/code)". The bracket sits between the two words the
        // phrase above matches on, so without this entry the single most common attribution string
        // in existence goes straight through.
        "generated with [claude",
        "generated by claude",
        "co-authored-by:",
        "co-authored by claude",
    ];

    /// <summary>
    /// Checks one piece of prose and returns what to do with it. Blank prose, and a project whose
    /// conventions state neither checkable rule, both come back untouched.
    /// </summary>
    public static WritingConventionsVerdict Vet(string? text, WritingConventions? conventions)
    {
        if (text.IsBlank())
        {
            return WritingConventionsVerdict.Untouched(text ?? string.Empty);
        }

        WritingConventions rules = conventions ?? WritingConventions.Default;
        bool checksEmDashes = rules.States(EmDashCues);
        bool checksAttribution = rules.States(AttributionCues);
        if (!checksEmDashes && !checksAttribution)
        {
            return WritingConventionsVerdict.Untouched(text);
        }

        List<string> rewrites = [];
        string[] lines = text.Replace("\r\n", "\n").Split('\n');
        bool[] verbatim = VerbatimLines(lines);
        List<string> kept = [];
        int attributionLinesDropped = 0;
        int emDashesRewritten = 0;
        int emDashesRemoved = 0;

        for (int index = 0; index < lines.Length; index++)
        {
            string line = lines[index];

            // A code block is somebody's output, a diff or a command line, and an em dash inside
            // one is data rather than punctuation. Rewriting it would corrupt exactly the thing the
            // block exists to reproduce verbatim, so a code block passes through whole.
            if (verbatim[index])
            {
                kept.Add(line);
                continue;
            }

            if (checksAttribution && AttributionIn(line) is { } phrase)
            {
                if (!IsAttributionAlone(line, phrase))
                {
                    return new WritingConventionsVerdict(
                        text,
                        rewrites,
                        $"the AI-attribution rule: \"{phrase}\" is welded into a sentence somebody wrote "
                        + $"({Legible(line)}), so there is no line to drop and no mechanical rewrite that "
                        + "keeps what the sentence says");
                }

                attributionLinesDropped++;
                continue;
            }

            if (!checksEmDashes || !line.Contains(EmDash))
            {
                kept.Add(line);
                continue;
            }

            kept.Add(WithoutEmDashes(line, ref emDashesRewritten, ref emDashesRemoved));
        }

        if (emDashesRewritten > 0)
        {
            rewrites.Add($"{emDashesRewritten} em dash{(emDashesRewritten == 1 ? string.Empty : "es")} rewritten as "
                + "a comma, a semicolon or a colon");
        }

        if (emDashesRemoved > 0)
        {
            // Counted and named apart from the rewritten ones rather than lumped in with them. A
            // dash that opened a line, ended one, or was the second of a pair somebody typed twice
            // leaves no mark behind it, and reporting it as one that became a comma would be a log
            // line stating something that did not happen (AGENTS.md: never guess at unobserved
            // facts. Pre-PR review cycle 1, adversarial lens).
            rewrites.Add(emDashesRemoved == 1
                ? "1 em dash removed with nothing in its place"
                : $"{emDashesRemoved} em dashes removed with nothing in their place");
        }

        if (attributionLinesDropped > 0)
        {
            rewrites.Add($"{attributionLinesDropped} AI-attribution line{(attributionLinesDropped == 1 ? string.Empty : "s")} dropped");
        }

        return rewrites.Count == 0
            ? WritingConventionsVerdict.Untouched(text)
            : new WritingConventionsVerdict(WithoutEdgeBlankLines(kept), rewrites, null);
    }

    /// <summary>
    /// The kept lines as one text, with the blank lines a dropped attribution left at either end
    /// removed and nothing else touched. Trimming characters rather than lines is what this
    /// replaced, and it reached past the blank lines it was after: a first line indented on purpose
    /// came back dedented, so a rewrite of one em dash elsewhere silently changed how markdown the
    /// check never flagged renders.
    /// </summary>
    private static string WithoutEdgeBlankLines(List<string> kept)
    {
        int first = 0;
        int last = kept.Count - 1;
        while (first <= last && kept[first].IsBlank())
        {
            first++;
        }

        while (last >= first && kept[last].IsBlank())
        {
            last--;
        }

        return string.Join('\n', kept.GetRange(first, last - first + 1));
    }

    /// <summary>
    /// Which lines of this text are verbatim rather than prose: every line of a fenced code block,
    /// its own two marker lines included, and every line of an indented code block. Both are
    /// markdown's way of saying "what follows is data", and an em dash or an attribution string
    /// inside either one is quoted rather than said.
    /// <para>
    /// Read as one pass over the whole text rather than line by line, because whether a fence
    /// opens a block is not a property of its own line. A fence that never closes is malformed
    /// markdown rather than a block, and reading it as one let every line after it past the check
    /// unseen, an attribution footer with a perfectly mechanical fix included (origin: pre-PR
    /// review cycle 1, conformance lens — agent output ending in an unclosed fence followed by
    /// "Generated with Claude Code" posted the attribution verbatim). The cost of the other
    /// direction is bounded and accepted: an em dash inside a block whose fence somebody forgot to
    /// close is rewritten as punctuation.
    /// </para>
    /// </summary>
    private static bool[] VerbatimLines(string[] lines)
    {
        bool[] verbatim = new bool[lines.Length];

        // Whether an indented line here would open an indented code block rather than carry on the
        // paragraph above it, which is markdown's own rule for the construct. True at the start of
        // the text, after a blank line, and after a fenced block, since a fence is not a paragraph
        // for an indented line to interrupt.
        bool canOpenIndentedCode = true;
        bool insideIndentedCode = false;
        for (int index = 0; index < lines.Length; index++)
        {
            if (FenceOpener(lines[index]) is { } opener)
            {
                int closing = ClosingFence(lines, index + 1, opener);
                if (closing >= 0)
                {
                    for (int inside = index; inside <= closing; inside++)
                    {
                        verbatim[inside] = true;
                    }

                    index = closing;
                    canOpenIndentedCode = true;
                    insideIndentedCode = false;
                    continue;
                }
            }

            if (lines[index].IsBlank())
            {
                canOpenIndentedCode = true;
                continue;
            }

            insideIndentedCode = IsIndentedFarEnough(lines[index]) && (insideIndentedCode || canOpenIndentedCode);
            verbatim[index] = insideIndentedCode;
            canOpenIndentedCode = false;
        }

        return verbatim;
    }

    /// <summary>A code fence's own marker: the character it is drawn with, and how long its run is.</summary>
    private readonly record struct CodeFence(char Marker, int Length);

    /// <summary>
    /// The fence this line could open, or null when it is not a fence line at all. Both markdown
    /// fence markers count, and a fence drawn inside a blockquote counts too: quoted output is the
    /// most common way a review reply carries somebody else's text, and reading its fence as prose
    /// would rewrite the very data the quote exists to reproduce.
    /// </summary>
    private static CodeFence? FenceOpener(string line)
    {
        string content = Unquoted(line);
        char marker = content.StartsWith("```", StringComparison.Ordinal) ? '`'
            : content.StartsWith("~~~", StringComparison.Ordinal) ? '~'
            : '\0';
        return marker == '\0' ? null : new CodeFence(marker, Run(content, 0, marker));
    }

    /// <summary>
    /// Which line closes this fence, or -1 when the text never does. Markdown's own two rules
    /// decide it, and both of them matter here: a closing fence is drawn with the same character,
    /// its run is at least as long as the opener's, and it carries nothing after that run but
    /// whitespace, since an info string belongs to an opener alone.
    /// <para>
    /// Reading every <c>```</c> line as the close of any open fence is what this replaced, and it
    /// broke exactly the construct fences exist for: a four-backtick fence quoting a
    /// three-backtick one was closed by the quoted block's own opener, so the quoted lines were
    /// vetted as prose and an em dash inside them was rewritten, misquoting the data under the
    /// owner's login (origin: pre-PR review cycle 1, adversarial lens).
    /// </para>
    /// </summary>
    private static int ClosingFence(string[] lines, int from, CodeFence opener)
    {
        for (int index = from; index < lines.Length; index++)
        {
            string content = Unquoted(lines[index]);
            int run = Run(content, 0, opener.Marker);
            if (run >= opener.Length && content[run..].IsBlank())
            {
                return index;
            }
        }

        return -1;
    }

    /// <summary>
    /// The line with its indentation and any blockquote markers taken off, which is where a fence
    /// marker sits when a reply is quoting somebody's output.
    /// </summary>
    private static string Unquoted(string line)
    {
        string content = line.TrimStart();
        while (content.StartsWith('>'))
        {
            content = content[1..].TrimStart();
        }

        return content;
    }

    /// <summary>How far a line has to be indented to be an indented code block's own, per markdown's rule.</summary>
    private const int IndentedCodeColumn = 4;

    /// <summary>
    /// Whether this line is indented far enough to be a line of an indented code block, markdown's
    /// other way of writing one. Whether it actually is one takes the line before it too, which is
    /// <see cref="VerbatimLines"/>'s job: indented code cannot interrupt a paragraph, and that rule
    /// is what keeps a wrapped bullet's own continuation line prose. A tab is the whole indent.
    /// <para>
    /// The approximation is deliberate and errs towards leaving prose alone: a nested list item or
    /// a paragraph indented this far inside a list item is read as code and goes unchecked, which
    /// is the direction every other miss in this checker errs in too (origin: pre-PR review cycle
    /// 1, adversarial lens — an em dash inside four-space-indented output was being rewritten as
    /// punctuation, misquoting the block).
    /// </para>
    /// </summary>
    private static bool IsIndentedFarEnough(string line) =>
        line.StartsWith('\t')
        || line.StartsWith(new string(' ', IndentedCodeColumn), StringComparison.Ordinal);

    /// <summary>
    /// How many characters of whitespace a line opens with, which is what a hand-drawn dash bullet
    /// keeps when its dash goes: the indentation is the line's place in a list rather than the
    /// dash's own spacing.
    /// </summary>
    private static int Indentation(string line)
    {
        int length = 0;
        while (length < line.Length && char.IsWhiteSpace(line[length]))
        {
            length++;
        }

        return length;
    }

    /// <summary>
    /// The attribution phrase this line claims, or null when it claims none. A phrase inside an
    /// inline code span does not count, for the reason an em dash inside one does not: what is in
    /// the span is quoted rather than said. A reply explaining that <c>Co-Authored-By:</c> must
    /// never be posted is discussing the footer, and a reply showing the reader the exact string is
    /// demonstrating it; reading either as the real thing would refuse the first outright (the
    /// phrase sits mid-sentence, which is the welded-in case) and silently delete the second's
    /// quote.
    /// </summary>
    private static string? AttributionIn(string line)
    {
        bool[] quoted = CodeSpans(line);
        return AttributionPhrases.FirstOrDefault(phrase => IsClaimedOutsideASpan(line, phrase, quoted));
    }

    /// <summary>
    /// Whether the line carries this phrase anywhere outside an inline code span. The phrase's
    /// first character decides the whole match: a span's edge is a backtick and no phrase carries
    /// one, so a match cannot straddle the boundary.
    /// </summary>
    private static bool IsClaimedOutsideASpan(string line, string phrase, bool[] quoted)
    {
        int index = line.IndexOf(phrase, StringComparison.OrdinalIgnoreCase);
        while (index >= 0)
        {
            if (!quoted[index])
            {
                return true;
            }

            index = line.IndexOf(phrase, index + 1, StringComparison.OrdinalIgnoreCase);
        }

        return false;
    }

    /// <summary>
    /// Whether the line is the attribution and nothing else, which is what makes dropping it
    /// mechanical. Leading whitespace, a markdown bullet or quote marker, and any run of
    /// non-letters (the robot emoji every one of these footers opens with) are all skipped first,
    /// because they are decoration on the attribution rather than words of the author's own.
    /// <para>
    /// What follows the phrase is read too, and that is the whole point of the method: an
    /// attribution footer trails a tool name, a link or a co-author's address, and nothing longer.
    /// A line that opens with the phrase and then keeps going in the author's own voice
    /// ("Generated with Claude and then rewritten against the spec by hand") is not the attribution
    /// alone, and dropping it would delete their sentence as silently as keeping it would post the
    /// attribution, so it takes the refusal path the welded-in case takes. Reading only the start
    /// of the line is what this replaced; the log line it produced said "1 AI-attribution line
    /// dropped" and named none of the prose that went with it.
    /// </para>
    /// </summary>
    private static bool IsAttributionAlone(string line, string phrase)
    {
        string remainder = line.TrimStart();
        while (remainder.Length > 0 && !char.IsLetter(remainder[0]))
        {
            remainder = remainder[1..].TrimStart();
        }

        return remainder.StartsWith(phrase, StringComparison.OrdinalIgnoreCase)
            && IsAttributionTail(remainder[phrase.Length..]);
    }

    /// <summary>
    /// How many words of its own an attribution footer's tail may carry before the line stops being
    /// an attribution and starts being a sentence. Four, measured against the footers this platform
    /// actually sees: "Code" after a markdown link, and a co-author's name before their address.
    /// </summary>
    private const int MaximumAttributionTailWords = 4;

    /// <summary>
    /// Whether what follows the attribution phrase is the footer's own tail rather than the
    /// author's prose. Every bound below is an approximation, and every one of them errs towards
    /// refusing to post over deleting somebody's words:
    /// <list type="bullet">
    /// <item>A link and an address, bracketed or bare, are the footer's own furniture and are not
    /// read at all, since the closing half of a markdown link ("Code](...)") is one word of tail
    /// rather than four.</item>
    /// <item>A tail that finishes a sentence and then keeps going is the author's own second
    /// sentence. A tail reading "Code. Reviewed manually." is the footer's own word for one word
    /// and the author's prose for two more, and dropping the line would delete the two.</item>
    /// <item>A tail word in lower case is prose too. Every tail this platform actually sees is a
    /// name, a tool's ("Code") or a person's ("Brian Hall"), and a name is capitalised. A letter
    /// that is neither case, which is every letter of a caseless script, is read as a name rather
    /// than as prose, since there the signal is not there to read.</item>
    /// <item>A conjunction or a relative pronoun anywhere in the tail is a sentence carrying on,
    /// wherever it sits: a name does not contain one, and reading only the tail's first word is
    /// what lets a continuation written in title case ("Code And Rewritten Since") past every
    /// other bound here.</item>
    /// <item>And at most <see cref="MaximumAttributionTailWords"/> words even when all of that
    /// holds.</item>
    /// </list>
    /// <para>
    /// None of them decides the general question, which needs a parser: they are the signals a
    /// mechanical read can be sure about, and a tail that fails any one of them takes the refusal.
    /// Origin incident (2026-09-09): this method's first cut bounded the tail by word count and by
    /// opening word alone, and both bounds passed the tail "Code. Reviewed manually." (three
    /// words, opening on a noun), so the line was dropped whole and the author's second sentence
    /// went with it, under a log line that said "1 AI-attribution line dropped" and named none of
    /// it.
    /// </para>
    /// </summary>
    private static bool IsAttributionTail(string tail)
    {
        string withoutFurniture = Address().Replace(Link().Replace(tail, " "), " ");
        if (KeepsGoingPastASentenceEnd(withoutFurniture))
        {
            return false;
        }

        List<string> words = LetterWords(withoutFurniture);
        return words.Count <= MaximumAttributionTailWords
            && words.TrueForAll(word => !char.IsLower(word[0]) && !SentenceCarriesOn.Contains(word));
    }

    /// <summary>The marks a sentence ends on, and the semicolon, which joins two that could have.</summary>
    private static readonly char[] SentenceEnds = ['.', '!', '?', ';'];

    /// <summary>
    /// Whether the tail ends a sentence and then says something else, which no footer does. Read
    /// once the furniture is out, so the dots of an address and of a link are not sentence ends,
    /// and satisfied only by a letter afterwards, so a footer's own closing full stop is not one
    /// either.
    /// </summary>
    private static bool KeepsGoingPastASentenceEnd(string tail)
    {
        int end = tail.IndexOfAny(SentenceEnds);
        return end >= 0 && tail[(end + 1)..].Any(char.IsLetter);
    }

    /// <summary>
    /// The tail's words. Letters only: what separates them is the footer's own punctuation, and a
    /// run of anything else is a separator rather than a word of the author's.
    /// </summary>
    private static List<string> LetterWords(string tail)
    {
        List<string> words = [];
        StringBuilder word = new();
        foreach (char character in tail)
        {
            if (char.IsLetter(character))
            {
                word.Append(character);
                continue;
            }

            if (word.Length > 0)
            {
                words.Add(word.ToString());
                word.Clear();
            }
        }

        if (word.Length > 0)
        {
            words.Add(word.ToString());
        }

        return words;
    }

    /// <summary>
    /// The words that, anywhere after an attribution phrase, mean the line is a sentence the
    /// author is still writing rather than a footer. Conjunctions, relative pronouns and the
    /// connectives that join a clause: the joins a mechanical read can be sure about, the same
    /// discipline <see cref="ClauseOpeners"/> keeps, and none of them a word a tool's name or a
    /// person's is made of. In lower case they would fail the case bound on their own, so what
    /// this list is really for is the same continuation written in title case.
    /// </summary>
    private static readonly HashSet<string> SentenceCarriesOn = new(StringComparer.OrdinalIgnoreCase)
    {
        "and", "but", "or", "nor", "yet", "so", "then", "plus", "also", "though", "although",
        "while", "because", "since", "after", "before", "when", "which", "who", "whom", "whose",
        "that", "however", "therefore", "except", "unless", "until", "whereas", "as", "to",
    };

    /// <summary>A link an attribution footer carries, bare or markdown, which is furniture rather than words.</summary>
    [GeneratedRegex(@"\]?\(?https?://\S*", RegexOptions.IgnoreCase)]
    private static partial Regex Link();

    /// <summary>
    /// A co-author's address, which is furniture for the same reason. Angle-bracketed as a git
    /// trailer writes it, and bare, so a trailer somebody typed without the brackets is read as
    /// the address it is rather than as three lower-case words of prose.
    /// </summary>
    [GeneratedRegex(@"<[^>]*>|\S+@\S+")]
    private static partial Regex Address();

    /// <summary>
    /// One line with every em dash replaced. A pair of them bracketing an aside becomes a pair of
    /// commas, which is the comma-bracketed twin of exactly the same sentence; any other em dash
    /// is replaced on its own by <see cref="Punctuation"/>. A dash with no clause on one side of
    /// it, which is a hand-drawn bullet or a dash that ended the line, is removed instead, and
    /// counted as removed rather than as rewritten.
    /// <para>
    /// An em dash inside an inline code span is left where it is, for the reason a fenced block is:
    /// a review reply quoting <c>expected — got nothing</c> is quoting data, and rewriting it would
    /// make the reply misquote the very output it is discussing. A line whose only em dashes are
    /// quoted that way comes back untouched, trailing whitespace included, since a markdown line
    /// break is two spaces nobody can see. A line that <em>is</em> rewritten keeps its own trailing
    /// whitespace for the same reason: dropping it would pull the next line into this one's
    /// rendered paragraph, which is a formatting change the em-dash rule never asked for and no
    /// reader of the diff can see.
    /// </para>
    /// </summary>
    private static string WithoutEmDashes(string line, ref int rewritten, ref int removed)
    {
        bool[] quoted = CodeSpans(line);
        List<int> dashes = [];
        for (int index = 0; index < line.Length; index++)
        {
            if (line[index] == EmDash && !quoted[index])
            {
                dashes.Add(index);
            }
        }

        if (dashes.Count == 0)
        {
            return line;
        }

        List<EmDashRun> runs = Runs(line, dashes);
        bool aside = runs.Count == 2
            && line[..runs[0].Start].IsNotBlank()
            && line[runs[0].End..runs[1].Start].IsNotBlank()
            && line[runs[1].End..].IsNotBlank();

        StringBuilder rebuilt = new();
        int cursor = 0;
        foreach (EmDashRun run in runs)
        {
            // Whitespace on the near side of the run goes with it: "a — b" has to become "a, b"
            // rather than "a , b", and an unspaced "a—b" still gets its space after the comma.
            int head = run.Start;
            while (head > cursor && char.IsWhiteSpace(line[head - 1]))
            {
                head--;
            }

            int tail = run.End;
            while (tail < line.Length && char.IsWhiteSpace(line[tail]))
            {
                tail++;
            }

            rebuilt.Append(line[cursor..head]);
            bool hasHead = rebuilt.ToString().IsNotBlank();
            bool hasTail = tail < line.Length;
            if (hasHead && hasTail)
            {
                rebuilt.Append(aside ? ',' : Punctuation(line[tail..]));
                rebuilt.Append(' ');
                rewritten++;
            }
            else
            {
                if (hasTail)
                {
                    // A dash opening a line is a bullet somebody drew by hand; there is no clause
                    // in front of it for punctuation to join, so it simply goes. What the line was
                    // indented by stays: that indentation is the line's place in a list rather
                    // than the dash's own spacing, and dropping it took a nested item out of its
                    // parent list (origin: pre-PR review cycle 1, conformance lens).
                    rebuilt.Clear();
                    rebuilt.Append(line[..Indentation(line)]);
                }

                removed++;
            }

            // Every dash of a run past its first leaves nothing behind whichever way the run went,
            // so it is counted where it belongs rather than reported as a mark nobody wrote.
            removed += run.Dashes - 1;
            cursor = tail;
        }

        rebuilt.Append(line[cursor..]);

        // The whitespace a rewrite left dangling at the end goes (an em dash that finished the
        // line took its clause's punctuation with it), but the line's own trailing whitespace is
        // put back: two spaces there are a markdown hard line break. A line the rewrite emptied
        // gets nothing back, since whitespace alone is not a break, it is a blank line.
        string rewrittenLine = rebuilt.ToString().TrimEnd();
        return rewrittenLine.Length == 0 ? rewrittenLine : rewrittenLine + line[line.TrimEnd().Length..];
    }

    /// <summary>
    /// A run of em dashes: where it starts, where it ends, and how many dashes it carries. Two
    /// dashes with nothing but whitespace between them are one mark somebody typed twice, not two
    /// marks bracketing a clause with nothing in it.
    /// </summary>
    private readonly record struct EmDashRun(int Start, int End, int Dashes);

    /// <summary>
    /// The line's em dashes grouped into runs. Reading each dash on its own is what this replaced,
    /// and the second dash of a pair found an empty clause in front of it and a mark already
    /// written behind it, so "a——b" came back as "a, , b" under a log line claiming two dashes had
    /// become punctuation (origin: pre-PR review cycle 1, adversarial lens).
    /// </summary>
    private static List<EmDashRun> Runs(string line, List<int> dashes)
    {
        List<EmDashRun> runs = [];
        foreach (int dash in dashes)
        {
            if (runs.Count > 0 && line[runs[^1].End..dash].IsBlank())
            {
                EmDashRun open = runs[^1];
                runs[^1] = open with { End = dash + 1, Dashes = open.Dashes + 1 };
                continue;
            }

            runs.Add(new EmDashRun(dash, dash + 1, 1));
        }

        return runs;
    }

    /// <summary>
    /// Which characters of this line sit inside an inline code span, marker backticks included. A
    /// span opens on a run of backticks and closes on the next run of exactly the same length,
    /// which is markdown's own rule and the only one that gets <c>``a ` b``</c> right; a run that
    /// never finds its match is punctuation somebody typed rather than a span, and the scan carries
    /// on past it.
    /// </summary>
    private static bool[] CodeSpans(string line)
    {
        bool[] inside = new bool[line.Length];
        int index = 0;
        while (index < line.Length)
        {
            if (line[index] != '`')
            {
                index++;
                continue;
            }

            int opening = Run(line, index, '`');
            int closing = ClosingRun(line, index + opening, opening);
            if (closing < 0)
            {
                index += opening;
                continue;
            }

            for (int quoted = index; quoted < closing + opening; quoted++)
            {
                inside[quoted] = true;
            }

            index = closing + opening;
        }

        return inside;
    }

    /// <summary>
    /// How long the run of <paramref name="marker"/> starting at this index is. One helper for
    /// both markers this file counts runs of, a code span's backticks and a code fence's own
    /// character, since two near-identical scans are two that drift.
    /// </summary>
    private static int Run(string text, int start, char marker)
    {
        int length = 0;
        while (start + length < text.Length && text[start + length] == marker)
        {
            length++;
        }

        return length;
    }

    /// <summary>Where the run of exactly <paramref name="length"/> backticks that closes a span starts, or -1.</summary>
    private static int ClosingRun(string line, int from, int length)
    {
        int index = from;
        while (index < line.Length)
        {
            if (line[index] != '`')
            {
                index++;
                continue;
            }

            int run = Run(line, index, '`');
            if (run == length)
            {
                return index;
            }

            index += run;
        }

        return -1;
    }

    /// <summary>
    /// Which mark replaces a lone em dash, decided from what follows it. A deliberate
    /// approximation, and named as one: telling an appositive from a second independent clause
    /// needs a parser, and the point here is that a reviewer never sees the dash, not that the
    /// replacement is the one the author would have picked.
    /// <list type="bullet">
    /// <item>A colon when the tail is an enumeration: it carries a comma and opens on nothing that
    /// starts a clause, which is the shape of a dash introducing a list.</item>
    /// <item>A semicolon when the tail opens with a word that starts an independent clause, where
    /// a comma would leave a comma splice.</item>
    /// <item>A comma otherwise, which is what an em dash setting off a trailing phrase or an
    /// appositive was standing in for, and the one substitution that is never ungrammatical
    /// there.</item>
    /// </list>
    /// </summary>
    private static char Punctuation(string tail)
    {
        int sentenceEnd = tail.IndexOfAny(['.', '!', '?']);
        string clause = sentenceEnd >= 0 ? tail[..sentenceEnd] : tail;
        string first = clause.Split([' ', ',', ';', ':'], StringSplitOptions.RemoveEmptyEntries).FirstOrDefault() ?? string.Empty;
        bool opensClause = ClauseOpeners.Contains(first.Trim('"', '\'', '`', '(', ')'));
        return clause.Contains(',') && !opensClause ? ':' : opensClause ? ';' : ',';
    }

    /// <summary>
    /// The words that, immediately after a dash, mean a second independent clause is starting.
    /// Pronouns and auxiliaries only: those are the openers a mechanical read can be sure about,
    /// and a list that reached for ordinary verbs would need to know which nouns they follow.
    /// </summary>
    private static readonly HashSet<string> ClauseOpeners = new(StringComparer.OrdinalIgnoreCase)
    {
        "it", "they", "he", "she", "we", "you", "i", "this", "that", "these", "those", "there",
        "is", "are", "was", "were", "has", "have", "had", "will", "would", "can", "could",
        "should", "must", "may", "might", "does", "do", "did", "nothing", "everything",
    };

    /// <summary>
    /// How much of an offending line a refusal is allowed to quote, and in what shape: the
    /// <c>BacklogPolicy.RelayedPolicy</c> convention, because this text goes into a log line an
    /// operator reads in a terminal and it came from an agent rather than from this platform.
    /// </summary>
    private const int MaximumQuotedLength = 120;

    /// <summary>
    /// The offending line, safe to print: bounded, and with everything a terminal would obey
    /// rather than show turned into a space. The rule is <see cref="WritingConventions.Illegible"/>
    /// rather than a second hand-written list, since two lists of layout overrides in one feature
    /// are two lists that drift.
    /// <para>
    /// Cut by text element, not by char, the same reason <c>PullRequestBody.CutAtWordBoundary</c>
    /// falls back to <c>RelayedText.CutLength</c>: a raw slice at a fixed index can land inside a
    /// surrogate pair, and half a character in a refusal is a refusal quoting text nobody wrote.
    /// </para>
    /// </summary>
    private static string Legible(string line)
    {
        StringInfo text = new(line.Trim());
        int kept = Math.Min(text.LengthInTextElements, MaximumQuotedLength);
        StringBuilder quoted = new();
        for (int index = 0; index < kept; index++)
        {
            foreach (char character in text.SubstringByTextElements(index, 1))
            {
                quoted.Append(WritingConventions.Illegible(character) ? ' ' : character);
            }
        }

        return kept < text.LengthInTextElements ? quoted.Append("...").ToString() : quoted.ToString();
    }
}
