using Hall9k.Domain.Infrastructure.Persistence;
using JasperFx;
using JasperFx.CodeGeneration;
using Marten;

namespace Hall9k.Cli.Infrastructure;

/// <summary>
/// The thin-writer store (Decisions Log #8): plain DocumentStore, no DI container, no
/// Wolverine host — h9k is execute-and-exit and gets called by agents mid-run.
/// </summary>
public static class CliStore
{
    public static DocumentStore Open() => DocumentStore.For(opts =>
    {
        opts.Connection(CliConfig.ConnectionString);
        opts.ConfigureHall9k(AutoCreate.CreateOnly);

        // Execute-and-exit means every invocation is a cold start. Auto mode loads the
        // pre-generated projection/session code compiled into this assembly (written to
        // Internal/Generated by a dev run, then built in); it self-heals by regenerating
        // when the model changes.
        opts.GeneratedCodeMode = TypeLoadMode.Auto;
        opts.SourceCodeWritingEnabled = true;
        opts.GeneratedCodeOutputPath = GeneratedCodePath();
    });

    private static string GeneratedCodePath()
    {
        // In a dev build, write into the project source tree so the next build compiles the
        // generated types into the assembly; anywhere else, fall back beside the binary.
        string binDir = AppContext.BaseDirectory;
        DirectoryInfo? projectDir = new DirectoryInfo(binDir).Parent?.Parent?.Parent;
        return projectDir is not null && File.Exists(Path.Combine(projectDir.FullName, "Hall9k.Cli.csproj"))
            ? Path.Combine(projectDir.FullName, "Internal", "Generated")
            : Path.Combine(binDir, "Internal", "Generated");
    }
}
