using FluentAssertions;
using Hall9k.Cli.Orchestrator;
using Xunit;

namespace Hall9k.Tests.Cli;

/// <summary>
/// The anchor's front matter and body are the whole contract (task: an operator starts a lean
/// node or project orchestrator window): a two-line do-not-edit notice, then instructions only —
/// handle a sibling <c>.new</c> file, read <c>recipes/orchestrator.md</c> and follow it, and name
/// the interim hand-written prototypes when that file does not exist yet.
/// </summary>
public sealed class LaunchAnchorDocumentTests
{
    [Fact]
    public void The_front_matter_is_a_two_line_do_not_edit_notice()
    {
        string rendered = LaunchAnchorDocument.Render();
        string[] lines = rendered.Split('\n');

        lines[0].Should().Be("---");
        lines[1].Should().Contain("Generated by").And.Contain("Do not edit");
        lines[2].Should().Contain("overwrites this file outright");
        lines[3].Should().Be("---");
    }

    [Fact]
    public void The_body_states_the_new_file_handling_the_handoff_and_the_missing_recipe_fallback()
    {
        string rendered = LaunchAnchorDocument.Render();

        rendered.Should().Contain(".new", "a re-run of the generator never overwrites, it writes a sibling instead");
        rendered.Should().Contain("adopt").And.Contain(".prev");
        rendered.Should().Contain("recipes/orchestrator.md");
        rendered.Should().Contain("orchestrator-recipe-generator");
        rendered.Should().Contain("~/.hall9k/recipes/orchestrator.md", "the node prototype is named as the interim recipe");
        rendered.Should().Contain(
            "~/.hall9k/projects/hall9k/recipes/orchestrator.md", "the hall9k project prototype is named as the interim recipe");
    }

    [Fact]
    public void The_first_step_registers_the_window_with_the_platform()
    {
        string rendered = LaunchAnchorDocument.Render();

        rendered.Should().Contain("h9k orchestrator register",
            "the platform learns an orchestrator is up here because the anchor says so first, not because anyone typed it");
        rendered.Should().Contain("--project").And.Contain("--session").And.Contain("--pid").And.Contain("--cli");
        rendered.Should().Contain("$CLAUDE_PID", "the process id is the one identity every vendor's CLI has");

        // Ordering, not mere presence: registration is step one, ahead of the .new comparison and
        // the hand-off to recipes/orchestrator.md, so a window that stops to ask the operator
        // about an adopted recipe file has already been recorded as live.
        int register = rendered.IndexOf("h9k orchestrator register", StringComparison.Ordinal);
        int newFileHandling = rendered.IndexOf(".new", StringComparison.Ordinal);
        int handoff = rendered.IndexOf("Read `recipes/orchestrator.md`", StringComparison.Ordinal);
        register.Should().BeGreaterThan(0);
        register.Should().BeLessThan(newFileHandling).And.BeLessThan(handoff);
    }

    [Fact]
    public void The_register_step_refuses_to_let_the_window_decide_a_replacement_on_its_own()
    {
        string rendered = LaunchAnchorDocument.Render();

        rendered.Should().Contain("--replace",
            "a refused registration has one lever, and the anchor has to name it");
        rendered.Should().Contain("let them decide",
            "which window wins is the operator's call, never the new window's");
    }

    [Fact]
    public void Writing_always_overwrites_whatever_was_there()
    {
        string path = Path.Combine(Path.GetTempPath(), $"launch-anchor-{Guid.NewGuid():N}.md");
        try
        {
            File.WriteAllText(path, "hand-written content that should not survive");

            LaunchAnchorDocument.Write(path);

            File.ReadAllText(path).Should().Be(LaunchAnchorDocument.Render());
        }
        finally
        {
            File.Delete(path);
        }
    }
}
