using FluentAssertions;
using Hall9k.Cli.Orchestrator;
using Xunit;

namespace Hall9k.Tests.Cli;

/// <summary>
/// The anchor's front matter and body are the whole contract (task: an operator starts a lean
/// node or project orchestrator window): a two-line do-not-edit notice, then instructions only —
/// handle a sibling <c>.new</c> file, read <c>recipes/orchestrator.md</c> and follow it, and name
/// the interim hand-written prototypes when that file does not exist yet.
/// </summary>
public sealed class LaunchAnchorDocumentTests
{
    [Fact]
    public void The_front_matter_is_a_two_line_do_not_edit_notice()
    {
        string rendered = LaunchAnchorDocument.Render();
        string[] lines = rendered.Split('\n');

        lines[0].Should().Be("---");
        lines[1].Should().Contain("Generated by").And.Contain("Do not edit");
        lines[2].Should().Contain("overwrites this file outright");
        lines[3].Should().Be("---");
    }

    [Fact]
    public void The_body_states_the_new_file_handling_the_handoff_and_the_missing_recipe_fallback()
    {
        string rendered = LaunchAnchorDocument.Render();

        rendered.Should().Contain(".new", "a re-run of the generator never overwrites, it writes a sibling instead");
        rendered.Should().Contain("adopt").And.Contain(".prev");
        rendered.Should().Contain("recipes/orchestrator.md");
        rendered.Should().Contain("orchestrator-recipe-generator");
        rendered.Should().Contain("~/.hall9k/recipes/orchestrator.md", "the node prototype is named as the interim recipe");
        rendered.Should().Contain(
            "~/.hall9k/projects/hall9k/recipes/orchestrator.md", "the hall9k project prototype is named as the interim recipe");
    }

    [Fact]
    public void Writing_always_overwrites_whatever_was_there()
    {
        string path = Path.Combine(Path.GetTempPath(), $"launch-anchor-{Guid.NewGuid():N}.md");
        try
        {
            File.WriteAllText(path, "hand-written content that should not survive");

            LaunchAnchorDocument.Write(path);

            File.ReadAllText(path).Should().Be(LaunchAnchorDocument.Render());
        }
        finally
        {
            File.Delete(path);
        }
    }
}
