using System.Text;
using Hall9k.Domain.Infrastructure.Ids;
using static Hall9k.Domain.Shared.Rendering.KnowledgeDocumentText;

namespace Hall9k.Domain.Features.Learning;

/// <summary>
/// Renders a project's live lessons as <c>lessons.md</c> (idea d805fd8b, piece 2; backlog 55):
/// the decisions document's sibling, deliberately the same shape, because the two are read side
/// by side and the difference that matters is what they carry rather than how they read.
/// <para>
/// A lesson is live the moment it is recorded — no quarantine, no corroboration gate
/// (IDEA-learning-capture, "Why there is no quarantine") — so this file carries lessons an
/// unattended agent wrote minutes ago beside ones a human typed. What it does not do is hide that
/// difference: every entry states whether it came from a run and how that run's attendance was
/// read, which is the provenance mark that makes live-at-once safe to read rather than a
/// quarantine that would cost the rediscovery the feature exists to prevent.
/// </para>
/// <para>
/// Determinism, node-local facts, and the retired-record rule are all
/// <see cref="Decision.DecisionsDocumentRenderer"/>'s, unchanged: see its doc for each, and
/// <c>KnowledgeDocumentText</c> for the mechanics both share.
/// </para>
/// </summary>
public static class LessonsDocumentRenderer
{
    /// <summary>
    /// The sentence marking this file as the platform's own render, checked before anything is
    /// overwritten — see <see cref="Decision.DecisionsDocumentRenderer.GeneratedMarker"/>.
    /// </summary>
    public const string GeneratedMarker = "Generated by `h9k` from the lesson store";

    public static string Render(IReadOnlyList<LearningDetails> lessons)
    {
        StringBuilder document = new();
        Line(document, "# Lessons");
        Line(document);
        Line(document,
            $"> {GeneratedMarker} (idea d805fd8b, backlog 55): a projection of the Learning streams, "
            + "rewritten whenever they change, so an edit here does not survive and is never committed. "
            + "Record a new one with `h9k learn \"<what you learned>\"` the moment a run learns it, and "
            + "cite it by the id in its heading.");
        Line(document);

        IReadOnlyList<LearningDetails> live = Live(lessons);
        if (live.Count == 0)
        {
            Line(document,
                "Nothing is recorded here yet. A lesson is one claim, phrased as an instruction to the "
                + "next agent and self-contained (no run ids, no paths from one worktree, nothing that only "
                + "makes sense inside the session that learned it): "
                + "`h9k learn \"On Windows, sed -i strips CRLF from this repo's files; match \\r?\\n instead\"`.");
            return document.ToString();
        }

        Line(document,
            $"{Count(live.Count, "lesson")} live here, oldest first. Each is live from the moment it "
            + "was recorded, with no review step, so read the provenance on one before leaning on it. A "
            + "retired lesson is not deleted, only left out of this file: `h9k learn list --all` shows "
            + "those, and a lesson that has stopped earning its line retires with "
            + "`h9k learn retire <id> --reason \"<why>\"`.");
        Line(document);
        Line(document,
            "Every live lesson is here, including ones a dispatched session's prompt is not given "
            + "(idea d805fd8b, piece 5). A lesson recorded by an agent run on another node is rendered "
            + "in this file for a reader and deliberately held out of the bounded section injected into "
            + "prompts, until the security review in idea 7e403b80 rules on it; `h9k learn show <id>` "
            + "says which side of that line a given lesson falls on, and why. So this file is the wider "
            + "set, not a duplicate of what any session was told.");

        foreach (LearningDetails lesson in live)
        {
            Line(document);
            Line(document, $"## {DomainId.Short(lesson.Id)}");
            Line(document);
            Line(document, Statement(lesson.Statement));
            Line(document);
            Line(document, $"- Recorded {Timestamp(lesson.RecordedAt)}{Provenance(lesson.Provenance)}.");
        }

        return document.ToString();
    }

    /// <summary>
    /// The lessons still worth carrying, in the one order every node derives the same way —
    /// <see cref="Decision.DecisionsDocumentRenderer"/>'s own binding filter, with retirement in
    /// place of supersession and <see cref="LearningStatus.Unknown"/> falling out the same way.
    /// </summary>
    private static IReadOnlyList<LearningDetails> Live(IReadOnlyList<LearningDetails> lessons) =>
        [.. lessons
            .Where(lesson => lesson.Status == LearningStatus.Active)
            .OrderBy(lesson => lesson.RecordedAt)
            .ThenBy(lesson => lesson.Id.ToString("N"), StringComparer.Ordinal)];
}
