using System.Text;
using Hall9k.Domain.Features.Tasks.Projections;
using Hall9k.Domain.Infrastructure.Extensions;
using Hall9k.Domain.Infrastructure.Ids;
using Hall9k.Domain.Infrastructure.Storage;
using Hall9k.Domain.Shared.ValueObjects;

namespace Hall9k.Domain.Features.Tasks.Rendering;

/// <summary>
/// Renders a <see cref="TaskDetails"/> as <c>task.md</c> (backlog 48): the store stays the
/// record, this is a browsable mirror. The shape matches the h9k task add/revise <c>--file</c>
/// format exactly (<see cref="Hall9k.Domain"/> knows nothing of the CLI's parser, but the
/// frontmatter keys and the body-is-agent-context rule are the same contract, kept in sync by
/// hand) — so what a human types back through <c>h9k task revise &lt;id&gt; --file</c> is what
/// they read here. The body carries only the agent context, on purpose: anything else placed in
/// it would round-trip into <c>AgentContext</c> on the next revise, silently corrupting the field
/// with rendered status noise. Everything else that is worth showing (state, model, external
/// reference) is frontmatter that the file parser already ignores as an unrecognized key, so it
/// is safe to add without touching what a revision reads back.
/// </summary>
public static class TaskDocumentRenderer
{
    /// <summary>Every render carries this line, so a direct edit is never mistaken for silence.</summary>
    public const string GeneratedMarker = "Generated by `h9k` from the task store";

    /// <summary>
    /// The directory a task renders under: short id plus a slug from the objective. Recomputed
    /// from whatever the objective reads now, so a revision that reworded it changes the answer —
    /// the caller is what moves the directory when this stops matching an existing one.
    /// </summary>
    public static string DirectoryName(TaskDetails task) => ProjectHomePaths.EntryDirectoryName(task.Id, task.Objective);

    public static string Render(TaskDetails task, string projectName)
    {
        string shortId = DomainId.Short(task.Id);
        StringBuilder document = new();

        document.AppendLine("---");
        document.AppendLine(
            $"# {GeneratedMarker}. Direct edits here are overwritten on the next task event — apply a "
            + $"change with `h9k task revise {shortId} --file <this file>` instead.");
        document.AppendLine($"id: {shortId}");
        document.AppendLine($"project: {projectName}");
        document.AppendLine($"state: {task.State.Value}");
        document.AppendLine($"type: {task.Type.Value}");
        if (task.Model != AgentModel.Unknown)
        {
            document.AppendLine($"model: {task.Model.Value}");
        }

        document.AppendLine($"objective: {OneLine(task.Objective)}");
        document.AppendLine("criteria:");
        foreach (string criterion in task.AcceptanceCriteria)
        {
            document.AppendLine($"- {OneLine(criterion)}");
        }

        if (task.BlockedBy.Count > 0)
        {
            document.AppendLine("blocked-by:");
            foreach (Guid dependency in task.BlockedBy)
            {
                document.AppendLine($"- {DomainId.Short(dependency)}");
            }
        }

        if (task.ExternalReference.IsNotBlank())
        {
            document.AppendLine($"external-reference: {OneLine(task.ExternalReference)}");
        }

        document.AppendLine("---");
        document.AppendLine();

        if (task.AgentContext.IsNotBlank())
        {
            document.AppendLine(task.AgentContext.Trim());
            document.AppendLine();
        }

        return document.ToString();
    }

    /// <summary>
    /// A frontmatter scalar reduced to one line: the file format has no quoting or escaping
    /// (<c>TaskFileParser</c> takes everything after the first colon verbatim), so a value with an
    /// embedded newline would silently truncate the field that follows it.
    /// </summary>
    private static string OneLine(string value) => value.ReplaceLineEndings(" ").Trim();
}
