<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>h9k</AssemblyName>
    <RootNamespace>Hall9k.Cli</RootNamespace>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>h9k</ToolCommandName>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console.Cli" />
    <PackageReference Include="NJsonSchema" />
    <PackageReference Include="Microsoft.Win32.Registry" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Hall9k.Domain.Infrastructure.Extensions" />
    <InternalsVisibleTo Include="Hall9k.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hall9k.Domain\Hall9k.Domain.csproj" />
    <ProjectReference Include="..\Hall9k.Connectors\Hall9k.Connectors.csproj" />
  </ItemGroup>

</Project>
