<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Using Include="Hall9k.Domain.Infrastructure.Extensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hall9k.Domain\Hall9k.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Hall9k.Tests" />
  </ItemGroup>

</Project>
