using System.Text;
using Hall9k.Domain.Features.Project.Projections;
using Hall9k.Domain.Infrastructure.Storage;

namespace Hall9k.Cli.ProjectHomes;

/// <summary>
/// The home's <c>AGENTS.md</c>: a render of project facts, never a hand-maintained file.
/// <para>
/// It exists so a session started in the project home bootstraps itself. It names the layout,
/// points at the repository's own <c>AGENTS.md</c> as the deep layer rather than restating it,
/// and lists the tool dependencies derived from the project's bindings — <c>h9k</c> always,
/// <c>gh</c> for a GitHub remote, the Atlassian CLI when a Jira board is bound. Everything in it
/// is read off <see cref="ProjectDetails"/>, which is what makes "rewritten when the facts
/// change" a mechanical guarantee instead of a promise: <c>project add</c>, <c>project init</c>
/// and <c>project set</c> all re-render it.
/// </para>
/// <para>
/// The same one-way-render ruling the task and idea files get (backlog 48): the store is the
/// record, the file is a browsable mirror, and a direct edit is overwritten by the next render.
/// The header line says exactly that, because a generated file that does not announce itself
/// gets hand-edited by the first person who reads it.
/// </para>
/// </summary>
public static class ProjectAgentsDocument
{
    /// <summary>
    /// The line every render carries, and the only signal this has for telling its own past output
    /// apart from a file that merely happens to sit at the same path. The render otherwise changes
    /// with every project fact, so byte-for-byte comparison to "the last thing we wrote" is not
    /// available; this substring is stable across every fact combination instead.
    /// </summary>
    private const string GeneratedMarker = "Generated by `h9k` from this project's registration";

    /// <summary>
    /// Whether a foreign (non-generated) <c>AGENTS.md</c> already sits at <paramref name="home"/>,
    /// checked before the recipe writes anything else into it. Only what the platform rendered is
    /// the platform's to overwrite, the same rule <see cref="SkillSeeder"/> applies to the
    /// canonical skill set. <see cref="ProjectHomeRecipe.BuildAsync"/> calls this first so the
    /// refusal costs nothing: without it, pointing <c>--home</c> at a directory that already holds
    /// an unrelated <c>AGENTS.md</c> (a checkout's own, for instance) had the recipe clone the
    /// repository, seed skills, and only then discover it could not finish, leaving a half-written
    /// home behind the refusal. Origin incident (2026-08-23): cycle 5 of this branch's pre-PR
    /// review traced <c>--home</c> pointed at an existing checkout and found the render replacing
    /// that checkout's own <c>AGENTS.md</c> while every step reported success; cycle 2's
    /// conformance pass then found the fix checking too late to spare the rest of the home.
    /// </summary>
    public static ProjectHomeStep? Guard(string home, string projectName)
    {
        string path = ProjectHomePaths.AgentsFile(home);
        if (!File.Exists(path))
        {
            return null;
        }

        string current = File.ReadAllText(path);
        return current.Contains(GeneratedMarker, StringComparison.Ordinal)
            ? null
            : ForeignContentFailure(path, projectName);
    }

    /// <summary>
    /// Renders the document and writes it. Returns the step line for the recipe's report.
    /// <para>
    /// Refuses when a file already sits at the path and does not carry <see cref="GeneratedMarker"/>,
    /// the same check <see cref="Guard"/> makes up front — kept here too as the last line of
    /// defence for any caller that writes without guarding first.
    /// </para>
    /// </summary>
    public static ProjectHomeStep Write(string home, ProjectDetails project)
    {
        string path = ProjectHomePaths.AgentsFile(home);
        string rendered = Render(home, project);
        bool existed = File.Exists(path);
        if (existed)
        {
            string current = File.ReadAllText(path);
            if (current == rendered)
            {
                return ProjectHomeStep.AlreadyThere($"AGENTS.md already matches the project's facts at {path}");
            }

            if (!current.Contains(GeneratedMarker, StringComparison.Ordinal))
            {
                return ForeignContentFailure(path, project.Name);
            }
        }

        File.WriteAllText(path, rendered);
        return existed
            ? ProjectHomeStep.Created($"AGENTS.md re-rendered from the project's facts at {path}")
            : ProjectHomeStep.Created($"AGENTS.md rendered from the project's facts at {path}");
    }

    private static ProjectHomeStep ForeignContentFailure(string path, string projectName) =>
        ProjectHomeStep.Failed(
            $"AGENTS.md at {path} was left alone: it already exists and does not carry the "
            + $"\"{GeneratedMarker}\" marker, so this recipe cannot tell it apart from hand-written "
            + "or pre-existing content it would otherwise destroy. Move it aside, or point --home "
            + $"at a directory of its own, then run h9k project init {projectName} — the project "
            + "is already registered by this point, so h9k project add cannot be re-run.");

    /// <summary>The document itself, separated from the write so it can be rendered and read in a test.</summary>
    public static string Render(string home, ProjectDetails project)
    {
        string bare = ProjectHomePaths.BareRepository(home, project.Name);
        string dev = ProjectHomePaths.DevWorktree(home);

        // Whether repo/ is actually populated is a filesystem fact, not a fact about the recorded
        // RepositoryPath: `h9k project init --keep-repo-path` materialises the bare clone and dev/
        // worktree without repointing the project at them, so ProjectCheckout.ForReading already
        // reads dev/ once it exists regardless of where dispatch cuts task worktrees from. Basing
        // this on RepositoryPath alone described a populated repo/ as empty in that case.
        bool repoMaterialised = Directory.Exists(dev);
        bool dispatchesFromHome = ProjectHomePaths.SameDirectory(project.RepositoryPath, bare);
        string code = repoMaterialised ? dev : project.RepositoryPath;
        StringBuilder document = new();

        document.AppendLine($"# {project.Name}: project home");
        document.AppendLine();
        document.AppendLine(
            "> Generated by `h9k` from this project's registration. Do not edit it: the next "
            + "`h9k project set` or `h9k project init` overwrites it. Change the facts "
            + "(`h9k project set " + project.Name + " …`) and the file follows.");
        document.AppendLine();
        document.AppendLine(
            "This directory is the whole boundary for working on this project. Everything below is "
            + "here on every machine the project is materialised on, so a session started here knows "
            + "where things are without hunting for them.");
        document.AppendLine();

        document.AppendLine("## Layout");
        document.AppendLine();
        document.AppendLine("```");
        document.AppendLine($"{home}");
        document.AppendLine("├── AGENTS.md   this file; generated, never hand-maintained");
        if (repoMaterialised)
        {
            document.AppendLine("├── repo/       the code");
            document.AppendLine($"│   ├── {Column(Path.GetFileName(bare))}the bare clone (git commands take -C this path)");
            document.AppendLine($"│   ├── {Column("dev/")}a worktree on {project.BaseBranch}; read and browse code here");
            document.AppendLine(dispatchesFromHome
                ? $"│   └── {Column("wt-*/")}task worktrees, created by dispatch, never by hand"
                : $"│   └── {Column("wt-*/")}none here: --keep-repo-path left dispatch cutting task "
                    + $"worktrees from {project.RepositoryPath}");
        }
        else
        {
            document.AppendLine("├── repo/       empty: this project was registered against a repository");
            document.AppendLine($"│                elsewhere, and dispatch cuts its worktrees from {code}");
        }

        document.AppendLine("├── ideas/      one directory per idea in discovery");
        document.AppendLine("├── tasks/      one directory per task; a task's runs live under it");
        document.AppendLine(
            $"│   └── {Column("_archive/")}terminal tasks only (closed out or abandoned); moved "
            + "back out automatically if reopened");
        document.AppendLine("├── skills/     skill docs: plain markdown, no vendor framing");
        document.AppendLine("└── .claude/    generated Claude Code plumbing (skills/ symlinked, never copied)");
        document.AppendLine("```");
        document.AppendLine();
        document.AppendLine(
            $"The deep layer is the repository's own guidance: read `{Path.Combine(code, "AGENTS.md")}` "
            + "(or the equivalent in the worktree you were given) for how this codebase is built, "
            + "tested and reviewed. This file names where things are; that one says how the work is done.");
        document.AppendLine();

        document.AppendLine("## Registration");
        document.AppendLine();
        document.AppendLine($"- Project: `{project.Name}` (id `{project.Id}`)");
        document.AppendLine(project.RepositoryUrl is { } url
            ? $"- Remote: {url}"
            : "- Remote: none recorded, so `repo/` cannot be materialised from anywhere");
        document.AppendLine($"- Primary branch: `{project.BaseBranch}`");
        if (!dispatchesFromHome)
        {
            document.AppendLine($"- Repository: `{project.RepositoryPath}`, outside this home");
        }

        document.AppendLine(project.JiraProjectKey.HasValue
            ? $"- Jira board: `{project.JiraProjectKey.Value}`"
            : "- Jira board: none bound");
        document.AppendLine();

        document.AppendLine("## Tools this project needs");
        document.AppendLine();
        foreach (string dependency in ToolDependencies(project))
        {
            document.AppendLine($"- {dependency}");
        }

        document.AppendLine();
        document.AppendLine(
            "A missing tool fails honestly at the moment it is used. `h9k doctor` (backlog 24) checks "
            + "the same list up front, from the same facts.");
        document.AppendLine();

        document.AppendLine("## Working here");
        document.AppendLine();
        document.AppendLine($"- `h9k project show {project.Name}`: registration, settings, task rollup");
        document.AppendLine($"- `h9k task list --project {project.Name}`: this project's live tasks, newest first "
            + "(add --include-archived for closed-out ones too)");
        document.AppendLine($"- `h9k idea add \"…\" --project {project.Name}`: capture something before it is a task");
        document.AppendLine("- `h9k status`: the attention pane across every project");
        document.AppendLine();
        document.AppendLine(
            "New work enters through `h9k task add`, then `h9k task publish <id> --assign`. Nothing "
            + "dispatches until a human publishes and assigns it.");

        return document.ToString();
    }

    /// <summary>
    /// The tool list, derived rather than declared: each entry is here because a binding on the
    /// project put it here, so a project that binds nothing lists only <c>h9k</c> and git and
    /// nobody installs an Atlassian CLI for a repository that has never seen Jira.
    /// </summary>
    public static IReadOnlyList<string> ToolDependencies(ProjectDetails project)
    {
        List<string> dependencies =
        [
            "`h9k`: the platform CLI. Every fact about this project is a query away; nothing here "
            + "requires knowing the runtime layout.",
            "`git`: `repo/` is a bare clone with worktrees cut from it.",
        ];

        if (project.RepositoryUrl is { Host: var host } && host.Contains("github", StringComparison.OrdinalIgnoreCase))
        {
            dependencies.Add(
                "`gh`: the remote is GitHub, and the platform's pull-request and issue work goes "
                + "through it. `gh auth login` then `gh auth setup-git` is what makes clones and "
                + "pushes here authenticate.");
        }

        if (project.JiraProjectKey.HasValue)
        {
            dependencies.Add(
                $"the Atlassian CLI: a Jira board (`{project.JiraProjectKey.Value}`) is bound, and "
                + "cards are authored by an agent session in this project rather than by the "
                + "platform, so the session needs a pen.");
        }

        return dependencies;
    }

    /// <summary>
    /// One entry of the tree's inner level, padded so the comments line up whatever the project
    /// is called. A long name pushes its own comment out by one space rather than being truncated:
    /// the name is the fact and the alignment is the decoration.
    /// </summary>
    private static string Column(string name) => name + new string(' ', Math.Max(1, 13 - name.Length));
}
