using Hall9k.Cli.ProjectHomes;
using Hall9k.Domain.Infrastructure.Storage;

namespace Hall9k.Cli.Orchestrator;

/// <summary>
/// The tiny, platform-owned file every orchestrator launch line appends as the window's system
/// prompt with <c>--append-system-prompt-file</c> (task: an operator starts a lean node or
/// project orchestrator window). Overwritten outright on every <c>h9k install</c>, <c>h9k
/// project add</c>, <c>h9k project init</c>, and project-home render — the
/// <c>PostgresRuntime.WriteComposeFile</c> discipline, not
/// <see cref="Hall9k.Cli.ProjectHomes.SkillSeeder"/>'s publish/shadow/retire one, because nothing ever hand-edits this file: it names no fact about
/// any one project or node, so there is nothing in it an operator would have reason to change.
/// <para>
/// It is deliberately tiny: it is loaded on every turn one, so its whole job is to point at the
/// generator-written <see cref="RecipeLibraryPaths.OrchestratorRecipeFileName"/> and hand off to
/// it, plus the <c>.new</c> handling a re-run of the generator relies on to never clobber a
/// recipe outright. Its content is otherwise identical wherever it is written, with one named
/// exception Decisions Log #147 sanctions: step 3's own fallback names two machine-specific,
/// hand-written prototype paths from before the generator existed (the node's own and the
/// hall9k project's own), for exactly the interim window between install and this skill's first
/// run.
/// </para>
/// </summary>
public static class LaunchAnchorDocument
{
    /// <summary>Identical content wherever it is written: the anchor names no project- or node-specific fact.</summary>
    public static string Render() =>
        """
        ---
        Generated by `h9k`. Do not edit: the next `h9k install`, `h9k project add`,
        `h9k project init`, or `h9k update` overwrites this file outright.
        ---

        # Orchestrator launch anchor

        This file is appended to this window's system prompt on every launch (`--append-system-prompt-file`).
        Keep it in mind that it is paid for on every turn one, so it carries a hand-off and nothing else.

        1. Look in the `recipes/` directory here for a `.new` file beside each file the generator
           itself writes (`recipes/orchestrator.md.new`, and so on: one per generator-written file
           a re-run regenerated). This never includes `settings.json` or this anchor itself —
           both are platform-owned and always overwritten outright, never given a `.new` sibling.
           For each `.new` file found: compare it against the file it sits beside, report to the
           human what changed and what would be lost by adopting it, and ask whether to adopt it
           (rename it over the current file, keeping a dated `.prev` copy of what it replaced),
           keep the current file untouched, or merge the two by hand. Never adopt silently.
        2. Read `recipes/orchestrator.md` in this same directory and follow it. That file, not
           this one, is the actual recipe: what this window is, its start-up sequence, and how it
           spawns scoped sessions.
        3. If `recipes/orchestrator.md` does not exist, stop here and tell the human to run the
           `orchestrator-recipe-generator` skill from this directory. Until it has run, this
           machine's own interim recipe — a hand-written prototype recorded before the generator
           existed, not a file this anchor can regenerate — sits at
           `~/.hall9k/recipes/orchestrator.md` for the node window, or
           `~/.hall9k/projects/hall9k/recipes/orchestrator.md` for the hall9k project window
           specifically. If the path recipes/orchestrator.md resolves to in this window is the
           same path just named, no interim copy was ever made on this machine: there is nothing
           to fall back to, and running the generator is the only way forward.
        """.ReplaceLineEndings("\n");

    /// <summary>Writes the anchor at <paramref name="path"/>, overwriting whatever was there. Always safe: see the type doc.</summary>
    public static void Write(string path)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(path) ?? ".");
        File.WriteAllText(path, Render());
    }

    /// <summary>The same write, reported as a <see cref="ProjectHomeStep"/> for the recipe's own report.</summary>
    public static ProjectHomeStep WriteStep(string path)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(path) ?? ".");
        bool existed = File.Exists(path);
        string rendered = Render();
        if (existed && File.ReadAllText(path) == rendered)
        {
            return ProjectHomeStep.AlreadyThere($"launch-anchor.md already current at {path}");
        }

        File.WriteAllText(path, rendered);
        return ProjectHomeStep.Created(existed
            ? $"launch-anchor.md re-rendered at {path}"
            : $"launch-anchor.md rendered at {path}");
    }
}
