using System.Text;
using Hall9k.Domain.Infrastructure.Extensions;
using Hall9k.Domain.Infrastructure.Ids;
using Hall9k.Domain.Infrastructure.Storage;

namespace Hall9k.Domain.Features.Idea.Rendering;

/// <summary>
/// Renders an <see cref="IdeaDetails"/> as <c>idea.md</c> (backlog 48): the same one-way-render
/// ruling as <see cref="Tasks.Rendering.TaskDocumentRenderer"/>, one lifecycle stage earlier.
/// There is no <c>--file</c> form of <c>h9k idea revise</c> — the command takes the note as a
/// plain argument — so the header teaches the human to paste the body back rather than pointing
/// at a flag that does not exist.
/// </summary>
public static class IdeaDocumentRenderer
{
    public const string GeneratedMarker = "Generated by `h9k` from the idea store";

    /// <summary>The directory an idea renders under: short id plus a slug from its current note text.</summary>
    public static string DirectoryName(IdeaDetails idea) => ProjectHomePaths.EntryDirectoryName(idea.Id, idea.Text);

    public static string Render(IdeaDetails idea, string projectName)
    {
        string shortId = DomainId.Short(idea.Id);
        StringBuilder document = new();

        document.AppendLine("---");
        document.AppendLine($"id: {shortId}");
        document.AppendLine($"project: {projectName}");
        document.AppendLine($"state: {idea.State.Value}");
        document.AppendLine($"revisions: {idea.Revisions}");
        if (idea.CutTaskIds.Count > 0)
        {
            document.AppendLine($"cut-tasks: {string.Join(", ", idea.CutTaskIds.Select(DomainId.Short))}");
        }

        if (idea.ConcludeReason is { } concludeReason && concludeReason.IsNotBlank())
        {
            document.AppendLine($"conclude-reason: {concludeReason.ReplaceLineEndings(" ").Trim()}");
        }

        if (idea.ArchiveReason is { } archiveReason && archiveReason.IsNotBlank())
        {
            document.AppendLine($"archive-reason: {archiveReason.ReplaceLineEndings(" ").Trim()}");
        }

        document.AppendLine("---");
        document.AppendLine();
        document.AppendLine(
            $"> {GeneratedMarker}. Direct edits here are overwritten on the next idea event; apply a "
            + $"change with `h9k idea revise {shortId} \"<new text>\"` (paste the body below as the "
            + "argument — there is no --file form for ideas).");
        document.AppendLine();
        document.AppendLine(idea.Text.Trim());
        document.AppendLine();

        return document.ToString();
    }
}
