using System.Text;
using Hall9k.Domain.Infrastructure.Ids;
using static Hall9k.Domain.Shared.Rendering.KnowledgeDocumentText;

namespace Hall9k.Domain.Features.Decision;

/// <summary>
/// Renders a project's binding decisions as <c>decisions.md</c> (idea d805fd8b, piece 2): the
/// same one-way-render ruling <see cref="Idea.Rendering.IdeaDocumentRenderer"/> already holds for
/// <c>idea.md</c>, applied to the thing PLAN.md §16 used to be. The file is a projection of the
/// Decision streams, so an edit to it is gone on the next render and the header says so.
/// <para>
/// <b>Deterministic by construction, because two nodes holding the same history must render the
/// same bytes.</b> Line endings are written as <c>\n</c> explicitly rather than through
/// <see cref="StringBuilder.AppendLine()"/>, the one timestamp is UTC and invariant, and the
/// order is derived from the records themselves (recorded-at, then the id as a tiebreak) rather
/// than taken from whatever order a query happened to return — see
/// <c>KnowledgeDocumentText</c> for each rule and why it is shared with the lessons render.
/// </para>
/// <para>
/// Nothing node-local reaches the document, which is the other half of that property. A project's
/// id is a per-install coordinate (<c>EventReplicationInbox</c> rewrites an incoming payload's
/// <c>projectId</c> and its <c>scopeId</c> to the receiver's own), so scope ids stay out
/// entirely, and the project is named by the directory the file sits in rather than by a line in
/// it.
/// </para>
/// <para>
/// Only binding decisions are rendered. A superseded one is never deleted and stays one
/// <c>h9k decide list --all</c> away, but a document agents read as the rulebook must not carry
/// rules that stopped binding.
/// </para>
/// <para>
/// One exception, and it is a signpost rather than a rule: a superseded decision that carries a
/// legacy citation is named in a closing list, by citation and id, with no statement. The
/// citations imported from PLAN.md §16 are written into source comments across this repository
/// and this file's own header tells a reader to search for them, so a citation whose entry is
/// simply absent reads as a dangling reference rather than as a rule that ended (independent
/// pre-PR review, cycle 1, conformance lens). Naming it without restating it is what keeps the
/// rulebook free of rules that stopped binding while still answering the reference.
/// </para>
/// </summary>
public static class DecisionsDocumentRenderer
{
    /// <summary>
    /// The sentence marking this file as the platform's own render, and the one thing a writer
    /// checks before overwriting anything: a <c>decisions.md</c> that does not carry it belongs to
    /// somebody else (a repository that tracks a file of that name) and is never clobbered.
    /// </summary>
    public const string GeneratedMarker = "Generated by `h9k` from the decision store";

    public static string Render(IReadOnlyList<DecisionDetails> decisions)
    {
        StringBuilder document = new();
        Line(document, "# Decisions");
        Line(document);
        Line(document,
            $"> {GeneratedMarker} (idea d805fd8b): a projection of the Decision streams, rewritten "
            + "whenever they change, so an edit here does not survive and is never committed. Record a "
            + "new one with `h9k decide \"<one claim>\"` and cite it by the id in its heading.");
        Line(document);

        IReadOnlyList<DecisionDetails> binding = Binding(decisions);
        IReadOnlyList<DecisionDetails> endedButCited = EndedButCited(decisions);
        if (binding.Count == 0)
        {
            Line(document,
                "Nothing is recorded here yet. A decision is one claim, stated as a rule rather than a "
                + "story, and self-contained enough to read on its own six months from now: "
                + "`h9k decide \"Agents never push; the daemon pushes every branch with --force-with-lease\" "
                + "--origin \"a plain push rejected two rebased follow-up branches, 2026-08-17\"`.");
            AppendEndedButCited(document, endedButCited);
            return document.ToString();
        }

        Line(document,
            $"{Count(binding.Count, "decision")} binding here, oldest first. A superseded decision is "
            + "not deleted, only left out of the rules: `h9k decide list --all` shows those, and "
            + "`h9k decide show <id>` shows one in full with its provenance.");

        if (binding.Any(decision => decision.LegacyId.IsNotBlank()))
        {
            Line(document);
            Line(document,
                "A heading carrying a second name in parentheses is a decision that predates this store "
                + "and kept the citation it already had, so a reference written elsewhere as "
                + "`Decisions Log #62` is found by searching this file for that text. The same entry is "
                + "cited in some places as `§16 #62` or `PLAN.md §16 #62`, which name the same number "
                + "under the section that used to hold it: search for `Decisions Log #62` to find those "
                + "too. Cite the id from here on; the older name is never minted again.");
        }

        foreach (DecisionDetails decision in binding)
        {
            Line(document);
            Line(document, $"## {DomainId.Short(decision.Id)}{LegacyCitation(decision.LegacyId)}");
            Line(document);
            Line(document, Statement(decision.Statement));
            Line(document);
            Line(document, $"- Recorded {Timestamp(decision.RecordedAt)}{Provenance(decision.Provenance)}.");
            if (decision.OriginIncident.IsNotBlank())
            {
                Line(document, $"- Origin incident: {SingleLine(decision.OriginIncident)}");
            }

            if (decision.Supersedes.Count > 0)
            {
                Line(document, $"- Supersedes: {string.Join(", ", Ordered(decision.Supersedes).Select(DomainId.Short))}");
            }
        }

        AppendEndedButCited(document, endedButCited);
        return document.ToString();
    }

    /// <summary>
    /// The closing signpost for a citation whose decision no longer binds: the citation, the id,
    /// and the command that shows it in full. Deliberately not the statement — this file is read
    /// as the rulebook, and a rule that stopped binding must not be readable here as though it
    /// had not. Written only when there is one, so an ordinary project's document ends where its
    /// last binding decision does.
    /// <para>
    /// The example command quotes the first citation in this project's own list rather than a
    /// fixed one, so the line a reader can copy is a line that works in the document they are
    /// actually holding.
    /// </para>
    /// </summary>
    private static void AppendEndedButCited(StringBuilder document, IReadOnlyList<DecisionDetails> endedButCited)
    {
        if (endedButCited.Count == 0)
        {
            return;
        }

        Line(document);
        Line(document, "## Ended, named here for the citations that still point at them");
        Line(document);
        Line(document,
            $"{Count(endedButCited.Count, "decision")} here, each one predating this store, each keeping "
            + "the citation it already had, and each since superseded. None of them binds and none is "
            + "restated: they are named so a reference written elsewhere lands somewhere rather than on "
            + "nothing. Read one in full, with the reason it ended, by the citation itself: "
            + $"`h9k decide show \"{SingleLine(endedButCited[0].LegacyId)}\"`.");
        Line(document);
        foreach (DecisionDetails decision in endedButCited)
        {
            Line(document, $"- {SingleLine(decision.LegacyId)} — now {DomainId.Short(decision.Id)}, superseded.");
        }
    }

    /// <summary>
    /// The citation an imported decision already answered to, printed in its own heading beside
    /// the id that supersedes it (idea d805fd8b, piece 3). This is what makes the citations
    /// already written across this repository resolve here: a reader who followed
    /// <c>Decisions Log #62</c> out of a source comment finds that text in this file's headings,
    /// and the id beside it is what a new citation uses. Empty for a natively recorded decision,
    /// which has no earlier name to answer to.
    /// </summary>
    private static string LegacyCitation(string? legacyId) =>
        legacyId.IsNotBlank() ? $" ({SingleLine(legacyId)})" : string.Empty;

    /// <summary>
    /// The decisions that still bind, in the one order every node derives the same way: when they
    /// were recorded, then the id itself, which is unique and identical on every node holding the
    /// stream. <see cref="DecisionStatus.Unknown"/> falls out with the superseded ones — a row
    /// whose status this build does not recognise is not something to assert binds.
    /// </summary>
    private static IReadOnlyList<DecisionDetails> Binding(IReadOnlyList<DecisionDetails> decisions) =>
        [.. decisions
            .Where(decision => decision.Status == DecisionStatus.Recorded)
            .OrderBy(decision => decision.RecordedAt)
            .ThenBy(decision => decision.Id.ToString("N"), StringComparer.Ordinal)];

    /// <summary>
    /// The decisions the closing signpost names: superseded, and carrying a citation from before
    /// this store. Superseded rather than "not binding", so a row whose status this build does not
    /// recognise is left out of both lists rather than asserted to have ended. Ordered the same
    /// way <see cref="Binding"/> is, for the same reason: two nodes holding the same history
    /// render the same bytes.
    /// </summary>
    private static IReadOnlyList<DecisionDetails> EndedButCited(IReadOnlyList<DecisionDetails> decisions) =>
        [.. decisions
            .Where(decision => decision.Status == DecisionStatus.Superseded && decision.LegacyId.IsNotBlank())
            .OrderBy(decision => decision.RecordedAt)
            .ThenBy(decision => decision.Id.ToString("N"), StringComparer.Ordinal)];
}
