using System.Text;
using Hall9k.Domain.Infrastructure.Ids;
using static Hall9k.Domain.Shared.Rendering.KnowledgeDocumentText;

namespace Hall9k.Domain.Features.Decision;

/// <summary>
/// Renders a project's binding decisions as <c>decisions.md</c> (idea d805fd8b, piece 2): the
/// same one-way-render ruling <see cref="Idea.Rendering.IdeaDocumentRenderer"/> already holds for
/// <c>idea.md</c>, applied to the thing PLAN.md §16 used to be. The file is a projection of the
/// Decision streams, so an edit to it is gone on the next render and the header says so.
/// <para>
/// <b>Deterministic by construction, because two nodes holding the same history must render the
/// same bytes.</b> Line endings are written as <c>\n</c> explicitly rather than through
/// <see cref="StringBuilder.AppendLine()"/>, the one timestamp is UTC and invariant, and the
/// order is derived from the records themselves (recorded-at, then the id as a tiebreak) rather
/// than taken from whatever order a query happened to return — see
/// <c>KnowledgeDocumentText</c> for each rule and why it is shared with the lessons render.
/// </para>
/// <para>
/// Nothing node-local reaches the document, which is the other half of that property. A project's
/// id is a per-install coordinate (<c>EventReplicationInbox</c> rewrites an incoming payload's
/// <c>projectId</c> and its <c>scopeId</c> to the receiver's own), so scope ids stay out
/// entirely, and the project is named by the directory the file sits in rather than by a line in
/// it.
/// </para>
/// <para>
/// Only binding decisions are rendered. A superseded one is never deleted and stays one
/// <c>h9k decide list --all</c> away, but a document agents read as the rulebook must not carry
/// rules that stopped binding.
/// </para>
/// </summary>
public static class DecisionsDocumentRenderer
{
    /// <summary>
    /// The sentence marking this file as the platform's own render, and the one thing a writer
    /// checks before overwriting anything: a <c>decisions.md</c> that does not carry it belongs to
    /// somebody else (a repository that tracks a file of that name) and is never clobbered.
    /// </summary>
    public const string GeneratedMarker = "Generated by `h9k` from the decision store";

    public static string Render(IReadOnlyList<DecisionDetails> decisions)
    {
        StringBuilder document = new();
        Line(document, "# Decisions");
        Line(document);
        Line(document,
            $"> {GeneratedMarker} (idea d805fd8b): a projection of the Decision streams, rewritten "
            + "whenever they change, so an edit here does not survive and is never committed. Record a "
            + "new one with `h9k decide \"<one claim>\"` and cite it by the id in its heading.");
        Line(document);

        IReadOnlyList<DecisionDetails> binding = Binding(decisions);
        if (binding.Count == 0)
        {
            Line(document,
                "Nothing is recorded here yet. A decision is one claim, stated as a rule rather than a "
                + "story, and self-contained enough to read on its own six months from now: "
                + "`h9k decide \"Agents never push; the daemon pushes every branch with --force-with-lease\" "
                + "--origin \"a plain push rejected two rebased follow-up branches, 2026-08-17\"`.");
            return document.ToString();
        }

        Line(document,
            $"{Count(binding.Count, "decision")} binding here, oldest first. A superseded decision is "
            + "not deleted, only left out of this file: `h9k decide list --all` shows those, and "
            + "`h9k decide show <id>` shows one in full with its provenance.");

        foreach (DecisionDetails decision in binding)
        {
            Line(document);
            Line(document, $"## {DomainId.Short(decision.Id)}");
            Line(document);
            Line(document, Statement(decision.Statement));
            Line(document);
            Line(document, $"- Recorded {Timestamp(decision.RecordedAt)}{Provenance(decision.Provenance)}.");
            if (decision.OriginIncident.IsNotBlank())
            {
                Line(document, $"- Origin incident: {SingleLine(decision.OriginIncident)}");
            }

            if (decision.Supersedes.Count > 0)
            {
                Line(document, $"- Supersedes: {string.Join(", ", Ordered(decision.Supersedes).Select(DomainId.Short))}");
            }
        }

        return document.ToString();
    }

    /// <summary>
    /// The decisions that still bind, in the one order every node derives the same way: when they
    /// were recorded, then the id itself, which is unique and identical on every node holding the
    /// stream. <see cref="DecisionStatus.Unknown"/> falls out with the superseded ones — a row
    /// whose status this build does not recognise is not something to assert binds.
    /// </summary>
    private static IReadOnlyList<DecisionDetails> Binding(IReadOnlyList<DecisionDetails> decisions) =>
        [.. decisions
            .Where(decision => decision.Status == DecisionStatus.Recorded)
            .OrderBy(decision => decision.RecordedAt)
            .ThenBy(decision => decision.Id.ToString("N"), StringComparer.Ordinal)];
}
